// server/server.js
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { createClient } from '@supabase/supabase-js';
import { z } from 'zod';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors({
  origin: '*',
  methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization']
}));

app.use(express.json({ limit: '10mb' }));

// Initialize Supabase Client
const supabaseUrl = process.env.SUPABASE_URL || 'https://kcodussczqgiagwtlrxw.supabase.co';
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseKey) {
  console.warn('[Warning] SUPABASE_SERVICE_ROLE_KEY is not defined in server/.env');
}

const supabase = createClient(supabaseUrl, supabaseKey || '');

// Gemini API Key
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;

// Validation Schema for Advisory Request
const advisorySchema = z.object({
  crop_name: z.string().min(1, 'Crop name is required'),
  symptoms: z.string().min(3, 'Symptoms description is required'),
  growth_stage: z.string().optional().default('Vegetative'),
  weather_condition: z.string().optional().default('Normal / Sunny'),
  soil_condition: z.string().optional().default('Loamy Soil'),
  crop_id: z.string().optional().nullable(),
  user_id: z.string().optional().default('farmer_demo_1')
});

// Helper: Call Gemini REST API with Structured Prompt
async function callGeminiAdvisor(payload) {
  const prompt = `
You are an expert Agronomist, Plant Pathologist, and Principal Agricultural Advisor for CropPilot AI.
Analyze the following crop diagnosis request and return a comprehensive, actionable, and scientifically accurate agricultural advisory.

Crop Information:
- Crop Name: ${payload.crop_name}
- Symptoms Observed: ${payload.symptoms}
- Growth Stage: ${payload.growth_stage}
- Weather / Climate: ${payload.weather_condition}
- Soil Condition: ${payload.soil_condition}

Respond strictly in valid JSON format matching this structure:
{
  "condition_identified": "Specific disease, pest infestation, or physiological disorder name",
  "pathogen_or_cause": "e.g., Fungal pathogen (Alternaria solani) or Nutrient deficiency",
  "severity": "Low" | "Moderate" | "High" | "Critical",
  "confidence_score": 95,
  "summary": "Brief 1-2 sentence overview of the diagnosis.",
  "immediate_actions": [
    "Step 1 to stop spread immediately",
    "Step 2"
  ],
  "organic_remedies": [
    { "remedy": "Neem oil spray (3-5 ml/L)", "application": "Spray early morning or late evening every 7 days" }
  ],
  "chemical_remedies": [
    { "remedy": "Copper Oxychloride or Mancozeb 75% WP", "application": "2g per liter water on affected foliage", "precautions": "Wear mask and adhere to safety pre-harvest intervals" }
  ],
  "preventive_measures": [
    "Ensure proper plant spacing for air circulation",
    "Practice crop rotation with non-host crops"
  ],
  "irrigation_advice": "Recommended watering schedule to prevent moisture-induced fungal spread",
  "fertilizer_advice": "Nutrient balancing advice (e.g. reduce excess nitrogen)",
  "disclaimer": "This advisory is generated by CropPilot AI based on symptom analysis. For severe or large-scale crop failures, consult your local district agricultural extension officer."
}
Only output the JSON object. Do not include markdown code block backticks.
`;

  const modelsToTry = ['gemini-3.7-flash', 'gemini-flash-latest', 'gemini-3.8-flash'];
  let lastError = null;

  for (const model of modelsToTry) {
    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`;
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: {
            temperature: 0.2,
            responseMimeType: "application/json"
          }
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.warn(`[Gemini] ${model} returned ${response.status}: ${errorText.slice(0, 100)}`);
        lastError = new Error(`Gemini error: ${errorText}`);
        continue;
      }

      const data = await response.json();
      const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (rawText) {
        const cleaned = rawText.replace(/```json/g, '').replace(/```/g, '').trim();
        return JSON.parse(cleaned);
      }
    } catch (e) {
      lastError = e;
    }
  }

  throw lastError || new Error('Failed to generate advisory from all models');
}

// ----------------- API ROUTES -----------------

// 1. Health Check
app.get('/api/health', async (req, res) => {
  let supabaseConnected = false;
  try {
    const { error } = await supabase.from('farms').select('count', { count: 'exact', head: true });
    supabaseConnected = !error;
  } catch (e) {
    supabaseConnected = false;
  }

  res.json({
    status: 'healthy',
    timestamp: new Date().toISOString(),
    services: {
      server: 'running',
      supabase: supabaseConnected ? 'connected' : 'error',
      gemini: !!GEMINI_API_KEY ? 'configured' : 'missing_key'
    }
  });
});

// 2. Farms Management
app.get('/api/farms', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('farms')
      .select('*, fields(*, crops(*))')
      .order('created_at', { ascending: false });

    if (error) throw error;
    res.json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/farms', async (req, res) => {
  try {
    const { name, location, total_area_acres, user_id } = req.body;
    if (!name || !location) {
      return res.status(400).json({ error: 'Name and location are required' });
    }

    const { data, error } = await supabase
      .from('farms')
      .insert([{ 
        name, 
        location, 
        total_area_acres: parseFloat(total_area_acres) || 0,
        user_id: user_id || 'farmer_demo_1' 
      }])
      .select()
      .single();

    if (error) throw error;
    res.status(201).json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// 3. Fields Management
app.post('/api/fields', async (req, res) => {
  try {
    const { farm_id, name, soil_type, irrigation_type, area_acres } = req.body;
    if (!farm_id || !name) {
      return res.status(400).json({ error: 'farm_id and name are required' });
    }

    const { data, error } = await supabase
      .from('fields')
      .insert([{
        farm_id,
        name,
        soil_type: soil_type || 'Loamy',
        irrigation_type: irrigation_type || 'Drip Irrigation',
        area_acres: parseFloat(area_acres) || 0
      }])
      .select()
      .single();

    if (error) throw error;
    res.status(201).json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// 4. Crops Management
app.get('/api/crops', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('crops')
      .select('*, fields(name, farms(name, location))')
      .order('created_at', { ascending: false });

    if (error) throw error;
    res.json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/crops', async (req, res) => {
  try {
    const { field_id, crop_name, variety, status, planting_date } = req.body;
    if (!field_id || !crop_name) {
      return res.status(400).json({ error: 'field_id and crop_name are required' });
    }

    const { data, error } = await supabase
      .from('crops')
      .insert([{
        field_id,
        crop_name,
        variety: variety || 'Standard',
        status: status || 'Healthy',
        planting_date: planting_date || new Date().toISOString().split('T')[0]
      }])
      .select()
      .single();

    if (error) throw error;
    res.status(201).json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// 5. AI Crop Advisory Diagnosis
app.post('/api/advisories/diagnose', async (req, res) => {
  try {
    const parseResult = advisorySchema.safeParse(req.body);
    if (!parseResult.success) {
      return res.status(400).json({ error: parseResult.error.errors[0].message });
    }

    const payload = parseResult.data;
    console.log(`[Diagnosis] Dispatching AI diagnosis for ${payload.crop_name}...`);

    // Call Gemini AI
    const aiResult = await callGeminiAdvisor(payload);

    // Save into Supabase Database
    const { data: savedAdvisory, error: dbError } = await supabase
      .from('advisories')
      .insert([{
        user_id: payload.user_id,
        crop_id: payload.crop_id || null,
        crop_name: payload.crop_name,
        symptoms: payload.symptoms,
        growth_stage: payload.growth_stage,
        weather_condition: payload.weather_condition,
        soil_condition: payload.soil_condition,
        diagnosis: aiResult.condition_identified,
        severity: ['Low', 'Moderate', 'High', 'Critical'].includes(aiResult.severity) ? aiResult.severity : 'Moderate',
        organic_remedies: aiResult.organic_remedies || [],
        chemical_remedies: aiResult.chemical_remedies || [],
        preventive_measures: aiResult.preventive_measures || [],
        irrigation_advice: aiResult.irrigation_advice || '',
        disclaimer: aiResult.disclaimer || '',
        raw_ai_response: aiResult
      }])
      .select()
      .single();

    if (dbError) {
      console.warn('[Database] Failed to persist advisory:', dbError.message);
    }

    res.json({
      success: true,
      advisory_id: savedAdvisory?.id || null,
      created_at: savedAdvisory?.created_at || new Date().toISOString(),
      diagnosis_data: aiResult
    });
  } catch (err) {
    console.error('[Diagnosis] Error processing request:', err);
    res.status(500).json({ error: err.message || 'Failed to generate advisory' });
  }
});

// 6. Advisories History
app.get('/api/advisories', async (req, res) => {
  try {
    const { data, error } = await supabase
      .from('advisories')
      .select('*')
      .order('created_at', { ascending: false });

    if (error) throw error;
    res.json(data);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.delete('/api/advisories/:id', async (req, res) => {
  try {
    const { id } = req.params;
    const { error } = await supabase
      .from('advisories')
      .delete()
      .eq('id', id);

    if (error) throw error;
    res.json({ success: true, message: 'Advisory deleted' });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Start Server
app.listen(PORT, () => {
  console.log(`[CropPilot AI Server] Running on http://localhost:${PORT}`);
  console.log(`[CropPilot AI Server] Supabase URL: ${supabaseUrl}`);
});
